### ISSUE TITLE
Sentry Node Support

### ISSUE THREAD

**Issue by ravenac95** [oasislabs/oasis-core#1752] opened 2019-05-28 15:28 UTC
Tracking issue for adding sentry node support

## Goal

As part of the a mainnet and/or global deployment we need to support sentry nodes to provide ingress into a private network without exposing validators and workers directly to the internet. 

## Linked Issues

* [x] Research: Determine Changes Required For Sentry Nodes (#1753)
* [x] Enable Tendermint Sentry Node in Ekiden-Node (#1828)
* [ ] Support access control policy filtering on GRPC proxies (#1829)
* [ ] Libp2p proxies (#1871)

**Comment by kostko** [comment] 2019-12-05 17:28
Closed as duplicate of #1578.

**Closed by kostko** 2019-12-05 17:28 UTC
Labels: c:ops, epic
